name = "BrenierTwoFluid"
uuid = "698bc5df-bacc-4e45-9592-41ae9e406d75"
authors = ["Tobias Blickhan <tobias.blickhan@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
