name: Documentation

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Documentation
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: julia-actions/setup-julia@latest
        with:
          version: '1'
      - name: Install dependencies
        run: julia --project=docs/ -e 'using Pkg; Pkg.add(url="https://github.com/ToBlick/BrenierTwoFluid.jl"); Pkg.instantiate();'
      - run: |
          julia --project=docs docs/make.jl html_output
      - uses: julia-actions/julia-buildpkg@v1
      - uses: julia-actions/julia-docdeploy@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          DOCUMENTER_KEY: ${{ secrets.DOCUMENTER_KEY }}